services:
  initializers:
    build: .
    command: bash -c "bin/rails db:migrate"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - tmp:/usr/src/app/tmp
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - proxysql
      - redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - tmp:/usr/src/app/tmp
    ports:
      - "3000:3000"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - initializers
  proxysql:
    image: proxysql/proxysql
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - db-primary
      - db-secondary
  db-primary:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password --general-log=1
    volumes:
      - db-primary:/var/lib/mysql
      - ./scripts/db-primary:/docker-entrypoint-initdb.d
  db-secondary:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --general-log=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-secondary:/var/lib/mysql
      - ./scripts/db-secondary:/docker-entrypoint-initdb.d

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  bundle:
  tmp:
  db-primary:
  db-secondary:
